version: '3.8'

services:
  backend:
    build: .
    ports:
      - "${PORT}:${PORT}"
    environment:
      - NODE_ENV=${NODE_ENV}
      - PORT=${PORT}
      - DB_NAME=${DB_NAME}
      - DB_USERNAME=${DB_USERNAME}
      - DB_PASSWORD=${DB_PASSWORD}
      - DB_HOST=${DB_HOST}
      - DB_PORT=${DB_PORT}
      - DATABASE_URL=${DATABASE_URL}
      - ALLOWED_ORIGINS=${ALLOWED_ORIGINS}
      - JWT_SECRET=${JWT_SECRET}
      - JWT_EXPIRES=${JWT_EXPIRES}
      - FRONTEND_URL=${FRONTEND_URL}
      - EMAIL_HOST_DEV=${EMAIL_HOST_DEV}
      - EMAIL_HOST_PROD=${EMAIL_HOST_PROD}
      - EMAIL_PORT_DEV=${EMAIL_PORT_DEV}
      - EMAIL_PORT_PROD=${EMAIL_PORT_PROD}
      - EMAIL_USERNAME_DEV=${EMAIL_USERNAME_DEV}
      - EMAIL_PASSWORD_DEV=${EMAIL_PASSWORD_DEV}
      - EMAIL_USERNAME_PROD=${EMAIL_USERNAME_PROD}
      - EMAIL_PASSWORD_PROD=${EMAIL_PASSWORD_PROD}
      - BREVO_API_KEY_PROD=${BREVO_API_KEY_PROD}
      - EMAIL_FROM=${EMAIL_FROM}
      - USER=${USER}
      - APP_PASSWORD=${APP_PASSWORD}
      - AWS_ACCESS_KEY_ID=${AWS_ACCESS_KEY_ID}
      - AWS_SECRET_ACCESS_KEY=${AWS_SECRET_ACCESS_KEY}
      - AWS_REGION=${AWS_REGION}
      - AWS_BUCKET_NAME=${AWS_BUCKET_NAME}
    volumes:
      - .:/app
      - /app/node_modules
    restart: unless-stopped

networks:
  default:
    driver: bridge


